### ISSUE TITLE
Broken UI

### ISSUE THREAD

**Issue by rc-ops** [HugoFara/lwt#32]
Extracted from #31 

**UI problems**
- There are a lot of UI buttons that aren't functional, in special the ones from the dropdown. 
- Also, you can see that after clicking on the checkbox to select the text and parse it, delete and et cetera, the dropdown to the right side of _Marked text_ doesn't became enabled, as you can see at the image below

>![1](https://user-images.githubusercontent.com/72221896/170493854-16adb09f-f4a0-4712-bbde-2dff835ec340.jpg)

**Desktop (please complete the following information):**
 - Same setup as last time, except this time Chromium has another version
 - OS: Windows 11 21H2 and Windows 10 20H2
- Browser: Chromium 101.0.4951.64
- EasyPHPDevserver-17 PHP 7.1.3

**Comment by HugoFara** [comment]
Hi!

I was able to reproduce your issue when installing version 2.4.0 without restarting the server, but once it was restarted everything went fine again. I'm not sure if your issue was something so simple, so I will let it open some days after publishing 2.4.1, so that you could tell me if it was linked to another bug fixed with 2.4.1...

**Comment by rc-ops** [comment]
Yes... I had to explicitly restart EasyPHP even though I had closed the program multiple times. Weird stuff :)
However #33 still persists.
Also, have you tested this fork with XAMPP? I can't make it work and I want to migrate from this obsolete PHP version that comes packed with easyphp.

**Comment by HugoFara** [comment]
Hello, for the Windows version I have been testing it with PHP 7.4 and XAMPP until now. As I am aware of the end-of-support for 7.4 by the end of the year, I will start using PHP 8.1, a compatibility patch may come as soon as the next release. Until then PHP 7.4 is the only version officially supported...
